### ISSUE TITLE
Travis is using JDK 8, breaking builds

### ISSUE THREAD

**Issue by c-x-berger** [wpilibsuite/SmartDashboard#115]
Title.

This should be easily fixable (change `jdk` to `oraclejdk11` in `.travis.yml`), but I'm not sure how to handle the `addons` section. [Travis docs](https://docs.travis-ci.com/user/languages/java/) seem to suggest that it could be simply removed?

**Comment by ThadHouse** [comment]
We're using azure now for all builds, so we will just disable the Travis builds.

**Comment by AustinShalit** [comment]
I've disabled travis building
