### ISSUE TITLE
SmartDashboard script error launching from DriverStation

### ISSUE THREAD

**Issue by tom131313** [wpilibsuite/SmartDashboard#116]
The SmartDashboard that is started automatically from the DriverStation (when you have the SmartDashboard selected) wants its configuration from:
C:\Users\your-name\Desktop\%PUBLIC%\frc2019\tools\SmartDashboard.vbs

That is wrong.  The C:\Users\your-name\Desktop\ is excessive - shouldn't be there - and duplicates the %PUBLIC% variable so the initiation fails.

SmartDashboard starts fine, if I start it myself.  I put a shortcut icon on my desktop for ease of starting it manually.

**Comment by ThadHouse** [comment]
This is a known issue in the Known Issues area of screensteps.

**Comment by tom131313** [comment]
Sorry.  I looked here for open and closed issues.  Will look at screensteps, too.  Thanks
