### ISSUE TITLE
Team Number cannot be set to localhost or IP in Preferences

### ISSUE THREAD

**Issue by samneff72** [wpilibsuite/SmartDashboard#152]
Hi WPI team, 

In WPI 2021 I opened up SmartDashboard and attempted to set my Preferences Team Number to the IP address of the Romi (10.0.0.2) and to localhost (one word no spaces or caps), and neither of them are being accepted by the field. 

I'm able to reset my team number from 841 to 804 or whatever, but when I enter localhost and press enter, it reverts to the previous team number. 

This is documented as the official way to access Simulation/Romi instances of SmartDashboard, at https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/smartdashboard/smartdashboard-intro.html

So looking for some guidance on alternative methods to get this working

**Comment by AustinShalit** [comment]
Hi. Can you please make sure your version of SmartDashboard is the most up to date version available? I just attempted this and was able to get it to work as expected. Please see the attached screenshot:

![image](https://user-images.githubusercontent.com/3799260/119753546-cd3fb700-be53-11eb-81f5-bf0f3bd9a5b2.png)

**Comment by samneff72** [comment]
Hi Austin, it worked for my student too. I don't know why my local install
is misbehaving.

I tried reinstalling WPI 2021.3.1 and the behavior hasn't changed.

Is there a method to explicitly uninstall SmartDashboard before
reinstalling? It's not available in my Windows "add or remove programs"
function...


Best Regards,
Sam Neff

**Comment by sciencewhiz** [comment]
How are you launching SmartDashboard?

**Comment by samneff72** [comment]
I've gotten bad results using the 'search bar' to pull it up & the desktop
shotcut...

Looking at the details of that shortcut, that shortcut is actually pointing
at 2020 SmartDashboard... and the search bar result is 2019 edition!
Double whoops.

Opening up 2021 SmartDashboard by going to
C:/user/public/wpilib/2021/tools...* this year's install works exactly as
described in the documentation. *

Issue can be closed, PBCK - thanks for helping me figure it out!


Best Regards,
Sam Neff

**Comment by sciencewhiz** [comment]
> Is there a method to explicitly uninstall SmartDashboard before reinstalling? It's not available in my Windows "add or remove programs" function... 

There isn't an automated uninstall for either just smart dashboard or all of wpilib but uninstall instructions are here: https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-2/wpilib-setup.html#uninstalling
