### ISSUE TITLE
SmartDashboard-2023.4.1-macarm64.jar missing on m1 mac in wpilib update

### ISSUE THREAD

**Issue by cosmosified** [wpilibsuite/SmartDashboard#172]
❯ ./gradlew build InstallAllTools  -Dorg.gradle.java.home="/Users/cmorton/wpilib/2023/jdk"
> Task :SmartDashboardInstall FAILED
Dependency Error!
GradleRIO detected this build failed due to missing dependencies!
Try again with `./gradlew build` whilst connected to the internet (not the robot!)
If the error persists, ensure you are not behind a firewall / proxy server (common in schools)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':SmartDashboardInstall'.
> Could not resolve all files for configuration ':wpiTools'.
   > Could not find SmartDashboard-2023.4.1-macarm64.jar (edu.wpi.first.tools:SmartDashboard:2023.4.1).
     Searched in the following locations:
         https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/tools/SmartDashboard/2023.4.1/SmartDashboard-2023.4.1-macarm64.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by cosmosified** [comment]
i did not have this issue updating to the previous versions of wpilib

**Comment by PeterJohnson** [comment]
SmartDashboard has never been available for Apple Silicon.  The issue regarding using GradleRIO to install it is wpilibsuite/GradleRIO#648. You can use the installer to upgrade all the other tools.

**Comment by cosmosified** [comment]
Ok it was ust that this update it gave an error and on prvious ones didn't. i'll checkout #648 . sorry for the duplicate.

**Comment by ThadHouse** [comment]
You probably hadn't ran InstallAllTools before. Its not possible for it to have worked this season on Apple Silicon macs. The installer doesn't run that task, and we generally recommend using the installer, so it was never noticed.

**Comment by PeterJohnson** [comment]
Fixed in wpilibsuite/GradleRIO#650.
