### ISSUE TITLE
LiveWindow display for PIDSubsystem doesn't show P,I,D,F values

### ISSUE THREAD

**Issue by chauser** [wpilibsuite/SmartDashboard#178]
PIDSubsystem uses a PIDEditor widget to handle the P,I,D,F fields of the controller in LiveWindow mode. However there is no display of these values. The CAN motor controller objects also use the PIDEditor for this purpose and there, it works. All of this observed using just LiveWindowFakeRobot server (not a real robot) so it could be something about the server or something about SmartDashboard itself. 
There's an open PR for allwpilib (https://github.com/wpilibsuite/allwpilib/pull/5352) that would deprecate PIDSubsystem in which case the correct fix for this issue is to remove the PIDSubsystem test code from LiveWindowFakeRobot.

**Comment by sciencewhiz** [comment]
I think there's a few different problems. It looks like in the transition from old commands to new commands, the PIDSubsystem layout changed, so FakeRobot needs update. However, when I tried running the GearsBot example to confirm the new layout, I didn't see the PID data in outline viewer, so there may also be a problem with allwpilib

**Comment by sciencewhiz** [comment]
The latter problem was my fault. I wasn't in test mode.
