### ISSUE TITLE
Numbers should be left justified

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/SmartDashboard#22]
A side effect of #14 is that if you have a full precision floating point value, and a box that is smaller then the number of digits, the test is right justified, and only shows the least significant part. 

EditorTextField calls setHorizontalAlignment(JTextField.LEFT), but that doesn't seem to be working

**Comment by AustinShalit** [comment]
I will take a stab at fixing this.  This was not introduced in #14.
