### ISSUE TITLE
gradle runs smartdashboard followed by FakeRobot

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/SmartDashboard#40]
When you run "/.gradlew run", it runs smartdashboard, and then when smartdashboard is closed, it runs FakeRobot. Normal use cases would be either just smartdashboard or smartdashboard and FakeRobot running at the same time, but not sequentially.

**Comment by AustinShalit** [comment]
I'll take this

**Comment by AustinShalit** [comment]
I cannot find a way to do this in our config.

`./gradlew :run` will only launch SmartDashboard and not FakeRobot.

**Comment by 333fred** [comment]
Yeah, `./gradlew run` will call `run` on every project. The only way to turn this off would be to make fakeRobot not have the application plugin.

**Comment by sciencewhiz** [comment]
Then we should update readme.md to say to use :run.
