### ISSUE TITLE
documentation for gradle

### ISSUE THREAD

**Issue by boyarsky** [wpilibsuite/SmartDashboard#65]
A student asked me about Gradle at this week's meeting. (I taught them Ant last year. They saw Smart Dashboard uses Gradle and asked about it.)  Not everyone was at the meeting so I wrote up everything I said and added more.

I was wondering if you'd like to link to it from the wiki (or copy it it into a wiki page). It basically explains what Gradle does in this project and walks through the build.gradle file.
https://www.selikoff.net/2017/01/14/building-smart-dashboard-with-gradle/

If not, no worries. It's already on the internet!

**Comment by 333fred** [comment]
While we would certainly accept a PR adding more documentation to our markdown (perhaps in a separate docs folder in allwpilib), we can't link to blogs with information that can potentially become outdated.

I read your article, and here's a couple of links and notes that should help you figure more stuff out. See here for the + in the versions: https://docs.gradle.org/2.11/userguide/dependency_management.html#sub:dynamic_versions_and_changing_modules. The wpilib versioning plugin source is here: https://github.com/wpilibsuite/wpilib-version-plugin. Note that you don't have to specify not to publish to Maven Central, that's something you have to specifically set up. The version plugin sets up publishing to a local maven repo instead, which on the offiical build server is our official maven server. I hope that helps explain a few things, feel free to respond with more questions.
