### ISSUE TITLE
Provide way to clear graphs

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/SmartDashboard#66]
Currently, SmartDashboard graphs can only be reset by closing and reopening the dashboard or changing the graph to a textbox and then back to a graph.  There should be a better way to do this.

Reported in: https://www.chiefdelphi.com/forums/showthread.php?threadid=154025

**Comment by Alex-Danielsen** [comment]
Currently, clearing a graph is a tedious job, that requires switching to editable, opening properties on each graph and clicking clear. It would greatly speed up development if there was a way to clear the graphs directly from them, without switching to editable or going into properties. And/or a global clear all graphs button, to aid when working with many graphs at the same time.
