### ISSUE TITLE
Publish a Release

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/SmartDashboard#8]
We should publish a release of SmartDashboard here on github.

**Comment by SamCarlberg** [comment]
Why? It's already bundled with the Eclipse plugins

**Comment by AustinShalit** [comment]
If I don't have eclipse downloaded at an event, I would not want to need to download Eclipse and follow all the steps to download the plugins. Publishing a jar here would reduce the amount of downtime when setting up a laptop.

**Comment by JLLeitschuh** [comment]
You can set up travis to automatically create a release when a commit on master is tagged and pushed.

**Comment by sciencewhiz** [comment]
I agree that SD should have a separate release. We use it on driver stations and non-programmers computers.

**Comment by 333fred** [comment]
@JLLeitschuh we we're going to have something do it, I'd rather have Jenkins. It should be the same build between here and in the plugins, not two separately-compiled jars.

**Comment by JLLeitschuh** [comment]
I mean it's incredibly easy to get travis to upload releases when a commit is tagged here and its something that anyone with the docs can configure.
Jenkins is a closed system that only a few people can modify.

Do you want to configure Jenkins to publish releases here? Seems like a lot of extra work.

**Comment by AustinShalit** [comment]
We could configure this tool on Jenkins to run when building plugins:

https://github.com/aktau/github-release

**Comment by sciencewhiz** [comment]
This shouldn't have been closed because the readme change suggested in #43 wasn't made.
