### ISSUE TITLE
Smart Dashboard doesn't launch

### ISSUE THREAD

**Issue by cjdenio** [wpilibsuite/SmartDashboard#99]
When I attempt to launch the Smart Dashboard from within Eclipse, nothing happens. I tried opening the `.jar` file, and even that doesn't work. Do I need to reinstall wpilib or the NI suite?

I'm using Java.

Thank you!

**Comment by PeterJohnson** [comment]
Do you have Java 9 installed?  The tools only support Java 8.

**Comment by cjdenio** [comment]
That would explain it. I'm the newest programmer on my FRC team, so I got Java 9.
Thank you for your time!
